@route = {{address}}/users

### Create test user

POST {{route}}
Content-Type: application/json

{
  "username": "StevenAlex",
  "password": "S+3v3n@1ex",
  "email": "steven_alex@mail.com",
  "first_name": "Steven",
  "last_name": "Alex"
}
