@route = {{address}}/users
@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJvYjEyMyIsImlhdCI6MTY0NDA3MjY3Mn0.9KmDvEdMXbarcRA8HkRoKRZrOejxXhSkXflmgo3OO6o

### Create new user

POST {{route}}
{{json}}

{
  "username": "Bob123",
  "password": "Bob123Builder",
  "email": "bob_staub_123@mail.com",
  "last_name": "Staub",
  "first_name": "Bob",
  "mobile_number": "12345678",
  "address": "Staub Street 123",
  "gender": "M"
}

### Login

POST {{route}}/auth/login
{{json}}

{
  "username": "Bob123",
  "password": "Bob123Builder"
}

### Get user profile by username

GET {{route}}/Bob123

### Get user profile as user

GET {{route}}/Bob123
{{authorization}}

### Edit user profile as user

PATCH {{route}}/Bob123
{{authorization}}
{{json}}

{
  "new_password": "Bob123Builder"
}
