@route = {{address}}/users

### Create new user

POST {{route}}
Content-Type: application/json

{
  "username": "Bob123",
  "password": "Bob123Builder",
  "email": "bob_staub_123@mail.com",
  "last_name": "Staub",
  "first_name": "Bob",
  "mobile_number": "12345678",
  "address": "Staub Street 123",
  "gender": "M"
}

### Login

POST {{route}}/login
Content-Type: application/json

{
  "username": "Bob123",
  "password": "Bob123Builder"
}

### Get user profile by username

GET {{route}}/Bob123

### Get user profile as user

GET {{route}}/Bob123
Content-Type: application/json

{
  "password": "Bob123Builder"
}

### Edit user profile as user

PATCH {{route}}/Bob123
Content-Type: application/json

{
  "password": "Bob123Builder",
  "mobile_number": "12345678"
}

### Delete user as user

DELETE {{route}}/Bob123
Content-Type: application/json

{
  "password": "Bob123Builder"
}

### Bookmark restaurant by restaurant ID

POST {{route}}/StevenAlex/bookmarks
Content-Type: application/json

{
  "password": "S+3v3n@1ex",
  "restaurant_id": 1
}

### Get bookmarks by username

GET {{route}}/StevenAlex/bookmarks
Content-Type: application/json

{
  "password": "S+3v3n@1ex"
}

### Unbookmark restaurant by restaurant ID

DELETE {{route}}/StevenAlex/bookmarks
Content-Type: application/json

{
  "password": "S+3v3n@1ex",
  "restaurant_id": 1
}

### Mark review as helpful by review ID

POST {{route}}/StevenAlex/helpful-marks
Content-Type: application/json

{
  "password": "S+3v3n@1ex",
  "review_id": 1
}

### Unmark review as helpful by review ID

DELETE {{route}}/StevenAlex/helpful-marks
Content-Type: application/json

{
  "password": "S+3v3n@1ex",
  "review_id": 1
}
