@route = {{address}}/reviews

### Create new review

POST {{route}}
Content-Type: application/json

{
  "password": "Bob123Builder",
  "username": "Bob123",
  "restaurant_id": 1,
  "rating": 2.5,
  "title": "Night at Prive",
  "description": "Prive go there. Food is great.",
  "image_url": "https://marinakeppelbay.com/wp-content/uploads/2020/09/BK-banner-image.jpg"
}

### Get review by ID

GET {{route}}/1

### Edit review by ID

PATCH {{route}}/1
Content-Type: application/json

{
  "password": "Bob123Builder",
  "username": "Bob123",
  "rating": 4.5
}
