@route = {{address}}/users/Bob123/helpful-marks

### Mark review as helpful by review ID

POST {{route}}
{{authorization}}
{{json}}

{
  "review_id": 1
}

### Get helpful marks by username

GET {{route}}
{{authorization}}
