@route = {{address}}/users/StevenAlex

### Unmark review as helpful by review ID

DELETE {{route}}/helpful-marks
Content-Type: application/json

{
  "password": "S+3v3n@1ex",
  "review_id": 1
}

### Delete review by ID

DELETE {{address}}/reviews/1
Content-Type: application/json

{
  "password": "S+3v3n@1ex",
  "username": "StevenAlex"
}

### Unbookmark restaurant by restaurant ID

DELETE {{route}}/bookmarks
Content-Type: application/json

{
  "password": "S+3v3n@1ex",
  "restaurant_id": 1
}

### Delete test user

DELETE {{route}}
Content-Type: application/json

{
  "password": "S+3v3n@1ex"
}
