@route = {{address}}/users/Bob123

### Unmark review as helpful by review ID

DELETE {{route}}/helpful-marks
{{authorization}}
{{json}}

{
  "review_id": 1
}

### Delete review by ID

DELETE {{address}}/reviews/1
{{authorization}}
{{json}}

{
  "username": "Bob123"
}

### Unbookmark restaurant by restaurant ID

DELETE {{route}}/bookmarks
{{authorization}}
{{json}}

{
  "restaurant_id": 1
}

### Logout

POST {{route}}/auth/logout
{{authorization}}

### Delete user by username

DELETE {{route}}
{{authorization}}
